# Generated by Django 6.0 on 2025-12-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJibon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_dham', models.CharField(max_length=255)),
                ('contact_shongjog', models.TextField()),
                ('skills_khomota', models.TextField()),
                ('experience_oviggota', models.JSONField(default=list)),
                ('education_porashona', models.JSONField(default=list)),
                ('created_at_sokale', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDujon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_rong', models.CharField(default='neon_sobuj', max_length=50)),
                ('slug_naam', models.SlugField(unique=True)),
                ('resume_ta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.resumejibon')),
            ],
        ),
        migrations.CreateModel(
            name='ChakriBakri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_nam', models.CharField(max_length=255)),
                ('job_description_bistari', models.TextField()),
                ('match_score_koto', models.FloatField(default=0.0)),
                ('missing_keywords_nai', models.JSONField(default=list)),
                ('resume_link_kora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakris', to='api.resumejibon')),
            ],
        ),
    ]
